export interface Entity {
  _id?: string; // Optional for creation
  companyId: string; // Refers to the Companies collection
  entityType: 'Customer' | 'Vendor' | 'Both';
  entityName: string;
  contactPerson?: ContactPerson;
  billingAddress?: Address;
  shippingAddress?: Address;
  taxInformation?: TaxInformation;
  accessStatus: 'Active' | 'Suspended' | 'Revoked' | 'Trial' | 'Expired';
  paymentHistory?: PaymentHistory[];
  nextPaymentDue?: Date;
  gracePeriod?: number; // Default: 0
  suspendedReason?: string;
  revokedReason?: string;

  // Soft Deletion and Auditing Fields
  isDeleted?: boolean; // Default: false
  createdBy: string; // Refers to the Users collection
  updatedBy?: string; // Refers to the Users collection
  deletedBy?: string; // Refers to the Users collection
  createdAt?: Date; // Auto-generated by Mongoose
  updatedAt?: Date; // Auto-generated by Mongoose
}

export interface ContactPerson {
  fullName?: string;
  email?: string;
  phone?: string;
}

export interface Address {
  street?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
}

export interface TaxInformation {
  taxId?: string;
  taxExempt?: boolean;
}

export interface PaymentHistory {
  invoiceId: string; // Refers to the Invoices collection
  amountPaid: number;
  paymentDate: Date;
}
