export interface Inventory {
  _id?: string; // Optional for creation
  companyId: string; // Refers to the Companies collection
  productId: string; // Refers to the Products collection
  barcode: string;
  batches: Batch[];
  totalQuantity: number; // Default: 0

  // Soft Deletion and Auditing Fields
  isDeleted?: boolean; // Default: false
  createdBy: string; // Refers to the Users collection
  updatedBy?: string; // Refers to the Users collection
  deletedBy?: string; // Refers to the Users collection
  createdAt?: Date; // Auto-generated by Mongoose
  updatedAt?: Date; // Auto-generated by Mongoose
}

export interface Batch {
  batchId: string;
  quantity: number;
  purchasePrice: number;
  sellingPrice: number;
  dateAdded?: Date; // Default: current date
}
