import {Batch} from './Batch';

export interface Product {
  _id?: string; // Optional for creation
  productName: string;
  sku: string;
  description?: string;
  category?: string;
  brandName?: string;
  modelNumber?: string;
  price: {
    unitPurchasePrice: number;
    retailPrice: number;
    taxInclusive?: boolean;
    taxPercentage?: number;
    discountPercentage?: number;
  };
  soldPrice?: number | null;
  soldDate?: Date | null;
  vendorId?: string; // Refers to the Entities collection
  companyId: string; // Refers to the Companies collection
  batches?: Batch[];
  isDeleted?: boolean; // Default false
  createdBy: string; // Refers to the Users collection
  updatedBy?: string; // Refers to the Users collection
  deletedBy?: string; // Refers to the Users collection
  createdAt?: Date; // Auto-generated by Mongoose
  updatedAt?: Date; // Auto-generated by Mongoose
}


